/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPage;

import Frame.Add;
import static Frame.Add.status;
import MyApp.FirstFrame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import newpackage.dbconnector;
import static Frame.Add.lname;
import static Frame.Add.fname;
import static Frame.Add.process;
import static Frame.Add.radiomale;
import static Frame.Add.radiofemale;
import static Frame.Add.add;
import static Frame.Add.status;
import static Frame.Add.process;
import javax.swing.table.*;
/**
 *
 * @author Quines
 */
public class manageUser extends javax.swing.JInternalFrame {
DefaultTableModel model;
    /**
     * Creates new form NewJInternalFrame
     */
    public manageUser() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        
        displayData();
    }

    public String gend;

    public void displayData() {

        try {

            dbconnector dbc = new dbconnector();
            ResultSet rs = dbc.getData("SELECT * FROM hris_emp");
            table.setModel(DbUtils.resultSetToTableModel(rs));
 DefaultTableModel model = (DefaultTableModel) table.getModel();
    String[] columnIdentifiers = {"ID", "Name", "Lastname", "Position","Address","Status", "Gender"};
    model.setColumnIdentifiers(columnIdentifiers);
        } catch (SQLException ex) {
            System.out.println("Error Message: " + ex);

        }
    }

    public void fillTable() throws SQLException {

        dbconnector dbc = new dbconnector();
        ResultSet rs = dbc.getData("SELECT * FROM hris_emp");
        table.setModel(DbUtils.resultSetToTableModel(rs));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        refresh = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setLayout(null);

        refresh.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        refresh.setText("refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel2.add(refresh);
        refresh.setBounds(710, 130, 120, 30);

        delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete);
        delete.setBounds(130, 130, 90, 30);

        add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add);
        add.setBounds(30, 130, 90, 30);

        edit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel2.add(edit);
        edit.setBounds(230, 130, 110, 30);

        jPanel8.setBackground(new java.awt.Color(153, 255, 204));
        jPanel8.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MANAGE USER");
        jPanel8.add(jLabel6);
        jLabel6.setBounds(60, 10, 310, 40);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(220, 20, 420, 60);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("HUMAN RESOURCE INFORMATION SYSTEM");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 90, 480, 22);
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 10, 160, 110);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 870, 170);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Lastname", "Position", "Address", "Status", "Gender"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 180, 690, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        displayData();
    }//GEN-LAST:event_refreshActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int rowIndex = table.getSelectedRow();
        if (rowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select a data first");
        } else {
            TableModel model = table.getModel();
            Object value = model.getValueAt(rowIndex, 0);
            String id = value.toString();
            int a = JOptionPane.showConfirmDialog(null, "Are you sure?");
            if (a == JOptionPane.YES_OPTION) {
                dbconnector dbc = new dbconnector();
                dbc.deleteData(Integer.parseInt(id));
                displayData();

            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        Add ad = new Add();
        FirstFrame main = (FirstFrame) SwingUtilities.getWindowAncestor(this);
        ad.setVisible(true);
        main.setVisible(false);
        process.setText("save");
        ad.action = "add";

    }//GEN-LAST:event_addActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

    }//GEN-LAST:event_tableMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed

        int rowindex = table.getSelectedRow();
        if (rowindex < 0) {
            JOptionPane.showMessageDialog(null, "Please Select Item");
        } else {
            Add ad = new Add();

            TableModel model = table.getModel();
            FirstFrame main = (FirstFrame) SwingUtilities.getWindowAncestor(this);
            ad.setVisible(true);
            ad.action = "update";
            process.setText("update");
            main.setVisible(false);
            ad.emp_id.setText("" + model.getValueAt(rowindex, 0));
            ad.lname.setText("" + model.getValueAt(rowindex, 1));
            ad.fname.setText("" + model.getValueAt(rowindex, 2));
             ad.position.setSelectedItem(model.getValueAt(rowindex, 3));
            ad.add.setText(""+model.getValueAt(rowindex, 4));
            
            ad.status.setSelectedItem(model.getValueAt(rowindex, 5));
            gend = model.getValueAt(rowindex, 6).toString();
            if(gend.equals("Male")){
             ad.radiomale.setSelected(true);
            }
            if(gend.equals("Female")){
             ad.radiofemale.setSelected(true);
            }
        }

    }//GEN-LAST:event_editActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh;
    public static javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
