/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userPage;

import MyApp.FirstFrame;
import static MyApp.RegisterForm.profile;
import static MyApp.RegisterForm.setPass;
import static MyApp.RegisterForm.setUser;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import newpackage.dbconnector;
import java.sql.*;

/**
 *
 * @author Hp
 */
public class timesheetLog extends javax.swing.JFrame {

    /**
     * Creates new form timesheetLog
     */
    public timesheetLog() {
        initComponents();
        connect();
    }
    PreparedStatement pst;
    Connection con;

    public void connect() {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hris", "root", "");
        } catch (SQLException e) {
            System.err.println("Cannot connect to database: " + e.getMessage());
        }
    }
    public boolean val(){
    String search = searchData.getText();
    if(search.equals("")){
    JOptionPane.showMessageDialog(this, "PLEASE ENTER EMPLOYEE ID");
      return  false;
    }
    return true;
    }
    int validateRegister() {
        int result;
        if ( jTimeIn.getText().isEmpty() || jTimeOut.getText().isEmpty()) {
            result = 0;
        } else {
            result = 1;
        }
        return result;
    }

    Color navcolor = new Color(22, 123, 123);
    Color headcolor = new Color(0, 102, 102);
    Color bodycolor = new Color(204, 204, 204);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: D o NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        time2 = new cambodia.raven.Time();
        time3 = new cambodia.raven.Time();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTimeOut = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTimeIn = new javax.swing.JTextField();
        time = new javax.swing.JButton();
        DateChooser = new com.toedter.calendar.JDateChooser();
        time1 = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        searchData = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        time2.setTextRefernce(jTimeIn);

        time3.setTextRefernce(jTimeOut);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTimeOut.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTimeOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTimeOutActionPerformed(evt);
            }
        });
        jPanel4.add(jTimeOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 220, 50));

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setText("TIME OUT:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 100, 60));

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 140, 40));

        jTimeIn.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTimeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTimeInActionPerformed(evt);
            }
        });
        jPanel4.add(jTimeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 220, 50));

        time.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        time.setText("...");
        time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });
        jPanel4.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 60, -1));

        DateChooser.setDateFormatString("dd-MM-yyyy");
        DateChooser.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jPanel4.add(DateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 240, 50));

        time1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        time1.setText("...");
        time1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        time1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time1ActionPerformed(evt);
            }
        });
        jPanel4.add(time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 60, -1));

        save.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel4.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 140, 40));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setText("SURNAME:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 100, 30));

        lname.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel4.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 220, 50));

        fname.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jPanel4.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 220, 50));

        searchData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDataActionPerformed(evt);
            }
        });
        jPanel4.add(searchData, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 220, 50));

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jButton5.setText("Find");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 140, 50));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setText("Search:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, 30));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setText("NAME:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, 30));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setText("Date:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 80, 60));

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setText("TIME IN:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, 60));

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 130, 600, 540);

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));
        jPanel3.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(153, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 255, 204));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EMPLOYEE'S TIME");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 310, 40));

        jPanel3.add(jPanel5);
        jPanel5.setBounds(130, 40, 350, 60);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setText("—");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel10);
        jLabel10.setBounds(10, 0, 40, 50);

        close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("x");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel11.add(close);
        close.setBounds(30, 0, 70, 50);

        jPanel3.add(jPanel11);
        jPanel11.setBounds(510, 0, 90, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(-10, -10, 620, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTimeOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTimeOutActionPerformed
       time.getText();
    }//GEN-LAST:event_jTimeOutActionPerformed

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setBackground(navcolor);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBackground(bodycolor);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FirstFrame us = new FirstFrame();
        this.dispose();
        us.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        time2.showPopup();
    }//GEN-LAST:event_timeActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        int b = JOptionPane.showConfirmDialog(null, "Confirm Exit?");
        if (b == JOptionPane.YES_OPTION) {
            FirstFrame ff = new FirstFrame();
            this.dispose();
            ff.setVisible(true);
        }
    }//GEN-LAST:event_closeMouseClicked

    private void time1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time1ActionPerformed
        time3.showPopup();
    }//GEN-LAST:event_time1ActionPerformed

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_saveMouseExited

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        int check = validateRegister();
        if (check == 1) {
            dbconnector dbc = new dbconnector();
            int result = dbc.insertData("INSERT INTO timeinput (Ts_id,T_date,T_in,T_out,T_id)VALUES('"+searchData.getText() + "','" + DateChooser.getDate() + "','" + jTimeIn.getText() + "','" + jTimeOut.getText() + "','" + searchData.getText() +"')");
            if (result == 1) {
                JOptionPane.showMessageDialog(null, "SUCCESSFULLY SAVE!");
                 FirstFrame us = new FirstFrame();
        this.dispose();
        us.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Saving data failed!");
                JOptionPane.showMessageDialog(null, "all fields are required!"); 
            }
        } else {
            JOptionPane.showMessageDialog(null, "all fields are required!");
        }
       
    }//GEN-LAST:event_saveActionPerformed

    private void searchDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDataActionPerformed
       

    }//GEN-LAST:event_searchDataActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(val()==true){ 
        try {
            pst = con.prepareStatement("SELECT emp_lname, emp_fname FROM hris_emp WHERE emp_id=?");
            int id = Integer.parseInt(searchData.getText());
            pst.setInt(1, id);
            ResultSet rs1 = pst.executeQuery();
            if (rs1.next() == false) {
                JOptionPane.showMessageDialog(null, "Sorry Record Not found");
                lname.setText(rs1.getString(""));
                searchData.requestFocus();
            } else {
            lname.setText(rs1.getString("emp_lname"));
            fname.setText(rs1.getString("emp_fname"));
            
            }
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
         }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void jTimeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTimeInActionPerformed
       time2.getText();
    }//GEN-LAST:event_jTimeInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timesheetLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timesheetLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timesheetLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timesheetLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timesheetLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JLabel close;
    private javax.swing.JTextField fname;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTimeIn;
    private javax.swing.JTextField jTimeOut;
    private javax.swing.JTextField lname;
    public static javax.swing.JButton save;
    private javax.swing.JTextField searchData;
    private javax.swing.JButton time;
    private javax.swing.JButton time1;
    private cambodia.raven.Time time2;
    private cambodia.raven.Time time3;
    // End of variables declaration//GEN-END:variables
}
